---
booktitle: 'Proceedings of the 5th International Workshop on Big Data, Streams and
  Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications
  at KDD 2016'
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 53
year: '2016'
shortname: BigMine
published: 2016-12-06
start: 2016-08-14
end: 2016-08-14
sections:
- name: front
  title: Front Matter
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: BIGMINE-2016
month: 0
cycles: false
editor:
- given: Wei
  family: Fan
- given: Albert
  family: Bifet
- given: Jesse
  family: Read
- given: Qiang
  family: Yang
- given: Philip S.
  family: Yu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 5th International Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications at KDD 2016
    Held in San Francisco, California, USA on 14 August 2016

  Published as Volume 53 by the Proceedings of Machine Learning Research on 06 December 2016.

  Volume Edited by:
    Wei Fan
    Albert Bifet
    Jesse Read
    Qiang Yang
    Philip S. Yu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 14 Aug
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v53"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v53
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: 'Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms,
    Systems, Programming Models and Applications'
  url: http://bigmine.github.io/bigmine16/
  location: San Francisco, California, USA
  dates:
  - 2016-08-14
  number: 5
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
