---
booktitle: 'Proceedings of the 5th International Workshop on Big Data, Streams and
  Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications
  at KDD 2016'
volume: 53
year: '2016'
shortname: BigMine
published: 2016-12-06
start: 2016-08-14
end: 2016-08-14
sections:
- name: front
  title: Front Matter
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: BIGMINE-2016
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Wei
  family: Fan
- given: Albert
  family: Bifet
- given: Jesse
  family: Read
- given: Qiang
  family: Yang
- given: Philip S.
  family: Yu
description: |
  Proceedings of the 5th International Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications at KDD 2016
    Held in San Francisco, California, USA on 14 August 2016

  Published as Volume 53 by the Proceedings of Machine Learning Research on 06 December 2016.

  Volume Edited by:
    Wei Fan
    Albert Bifet
    Jesse Read
    Qiang Yang
    Philip S. Yu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 14 Aug
url: http://proceedings.mlr.press
baseurl: "/v53"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v53
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: 'Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms,
    Systems, Programming Models and Applications'
  url: http://bigmine.github.io/bigmine16/
  location: San Francisco, California, USA
  dates:
  - 2016-08-14
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v53.bib
